version: "3.9"

services:
  frontend:
    build:
      context: ./notes-sharing-app-fe
      dockerfile: Dockerfile
    container_name: notes-sharing-app-fe
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - ./notes-sharing-app-fe/src:/app/src
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: ./notes-sharing-app-be
      dockerfile: Dockerfile
    container_name: notes-sharing-app-be
    ports:
      - "4000:4000"
    env_file:
      - ./notes-sharing-app-be/.env
    volumes:
      - ./notes-sharing-app-be/keys:/app/keys
    command: ./server
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:latest
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge