version: "3.9"

services:
  frontend:
    build:
      context: ./notes-sharing-app-fe
      dockerfile: Dockerfile
    container_name: notes-sharing-app-bee
    ports:
      - "3000:3000"
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://backend:4000
    # commands : "npm start"    
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: ./notes-sharing-app-be
      dockerfile: Dockerfile
    container_name: notes-sharing-app-bee
    ports:
      - "4000:4000"
    # environment:
    #   - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb?sslmode=disable
    # commands : "go run cmd/server/main.go"    
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:latest
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge
